<?php
/**
 * The template for displaying the fancybox modal window
 *
 * Displays modal window generated by fancybox-param.js.
 */
?>
<div id="fn-modal">
	<img id="fn-modal-image" />
	<h1 id="fn-modal-title"></h1>
	<p id="fn-modal-price"></p>
</div>
